name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    defaults:
      run:
        working-directory: agenda

    steps:
      - name: Baixar código
        uses: actions/checkout@v6

      - name: Configurar Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: agenda/package-lock.json

      - name: Instalar dependências
        run: npm ci

      - name: Compilar Angular
        run: npm run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Preparar arquivos
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./agenda/dist/agenda/browser

      - name: Publicar
        id: deployment
        uses: actions/deploy-pages@v4